// tgmrf.h
// Templated C++ fast backend for user-defined GMRF latent blocks (the
// `tgmrf_cpp()` constructor on the R side; the `tgmrf()` R-closure path
// lives in R/tgmrf.R).
//
// ============================================================================
// Design sketch
// ============================================================================
//
// The R-closure path (`tgmrf()`) ships a user closure `Q(theta)` and
// `prior(theta)`; the nested-Laplace driver calls them once per outer-grid
// point on the R side, precomputes a CSC triple, then ships the triples
// through to `cpp_nested_laplace_multi`. The C++-backend path
// (`tgmrf_cpp()`) does the same thing, except `Q(theta_k)` is evaluated in
// compiled C++ via a function pointer stored in a process-global registry
// rather than via Rcpp::Function. The downstream wire format (CSC triples +
// logdet + log_prior_theta) is identical between the two paths, so
// consumers (formula parser, inference layers, S3 methods) are not aware of
// which one is in use.
//
// A user-supplied .cpp file looks like:
//
//   // [[Rcpp::depends(tulpa, RcppEigen)]]
//   #include <tulpa/tgmrf.h>
//
//   template <typename T>
//   Eigen::SparseMatrix<T> my_Q(
//       const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta) {
//       // ... build Q in templated arithmetic
//   }
//
//   template <typename T>
//   Eigen::Matrix<T, Eigen::Dynamic, 1> my_mu(
//       const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta) {
//       // optional - return empty for zero mean
//       return Eigen::Matrix<T, Eigen::Dynamic, 1>();
//   }
//
//   template <typename T>
//   T my_log_prior(const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta) {
//       // user log-prior on theta
//   }
//
//   TULPA_REGISTER_TGMRF("my_periodic_ar1", my_Q, my_mu, my_log_prior)
//
//   // Rcpp::sourceCpp requires at least one explicit `// [[Rcpp::export]]`
//   // marker before it will dyn.load() the compiled DLL -- without the load,
//   // the static initializer never fires and the spec is never registered.
//   // Expose a tiny id-getter so the R constructor can verify the file was
//   // loaded and the id matches what tgmrf_cpp() was called with. The body
//   // is generated by the macro above; this comment plus the prototype on
//   // its own line is the part Rcpp scans for.
//
//   // [[Rcpp::export]]
//   std::string tulpa_tgmrf_cpp_id();
//
// Calling the macro:
//   1. Emits explicit instantiations of build_Q<T> / build_mu<T> /
//      log_prior_theta<T> at T = double, T = arena::Var, T = fwd::Dual so
//      the same source compiles against every AD type tulpa uses. (Only
//      `double` is currently exercised by inference; the AD slots are
//      reserved.)
//   2. Defines a static initializer that registers the resulting
//      `TgmrfSpec` under the provided id at DLL load time, by retrieving
//      the `tulpa_register_tgmrf` C callable exported by libtulpa.
//
// The R constructor `tgmrf_cpp()` compiles the file via Rcpp::sourceCpp,
// then looks up the spec by `id` and reads back `theta_dim` / `n_latent` /
// the sparsity pattern via one driver-side `Q(init)` evaluation.
//
// ============================================================================
// ABI / registration
// ============================================================================
//
// Registration goes through the registered C callable
// `R_RegisterCCallable("tulpa", "tulpa_register_tgmrf", ...)` exported by
// libtulpa (see src/tgmrf_registry.cpp). The user's DLL fetches the
// function pointer at DLL load via `R_GetCCallable` and forwards a
// `TgmrfSpec` POD. This keeps the user's DLL ABI-decoupled from libtulpa's
// internal registry implementation -- adding a field to the registry's
// data structure does not require recompiling user DLLs as long as
// `TgmrfSpec` stays append-only.

#ifndef TULPA_TGMRF_H
#define TULPA_TGMRF_H

#include <Rcpp.h>
#include <RcppEigen.h>
#include <Eigen/SparseCore>
#include <R_ext/Rdynload.h>
#include <cstdint>
#include <cstring>
#include <string>

#include "tulpa/model_data.h"          // TULPA_ABI_VERSION
#include "tulpa/autodiff_arena.h"      // tulpa::arena::Var
#include "tulpa/autodiff_fwd.h"        // ::fwd::Dual

namespace tulpa {
namespace tgmrf_backend {

// ----------------------------------------------------------------------------
// AD type aliases re-exported with stable names.
//
// Three instantiations are emitted by the registration macro:
//   * T = double                   -> evaluated at outer-grid points
//   * T = tulpa::arena::Var        -> reserved for future arena-AD gradient
//   * T = ::fwd::Dual              -> reserved for future fwd-AD gradient
//
// Only `T = double` is exercised by the current inference layers. The
// other two slots are reserved so that NUTS-over-theta (currently routed
// through FD in R) can later switch to AD without breaking user DLLs.
// ----------------------------------------------------------------------------
using A    = tulpa::arena::Var;
using A_fd = ::fwd::Dual;

// ----------------------------------------------------------------------------
// TgmrfSpec: POD registration structure carrying function pointers and
// metadata. Append-only: new fields go at the end and default to safe
// zero/null values so user DLLs compiled against an earlier layout keep
// binding.
// ----------------------------------------------------------------------------
template <typename T>
using TgmrfQFn = Eigen::SparseMatrix<T> (*)(
    const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta);

template <typename T>
using TgmrfMuFn = Eigen::Matrix<T, Eigen::Dynamic, 1> (*)(
    const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta);

template <typename T>
using TgmrfLogPriorFn = T (*)(
    const Eigen::Matrix<T, Eigen::Dynamic, 1>& theta);

struct TgmrfSpec {
    // ABI version this spec was compiled against. Set automatically by the
    // registration macro.
    int abi_version = TULPA_ABI_VERSION;

    // Function pointers - instantiated for double, A (arena AD), A_fd
    // (forward AD).
    TgmrfQFn<double>        Q_double          = nullptr;
    TgmrfMuFn<double>       mu_double         = nullptr;
    TgmrfLogPriorFn<double> log_prior_double  = nullptr;

    TgmrfQFn<A>             Q_arena           = nullptr;
    TgmrfMuFn<A>            mu_arena          = nullptr;
    TgmrfLogPriorFn<A>      log_prior_arena   = nullptr;

    TgmrfQFn<A_fd>          Q_fwd             = nullptr;
    TgmrfMuFn<A_fd>         mu_fwd            = nullptr;
    TgmrfLogPriorFn<A_fd>   log_prior_fwd     = nullptr;
};

// ----------------------------------------------------------------------------
// Registration call signature: `tulpa_register_tgmrf(id, spec)`.
//
// User DLLs do not call this directly. The registration macro emits a
// static initializer that retrieves the function pointer via
// `R_GetCCallable("tulpa", "tulpa_register_tgmrf")` and forwards the
// spec it built from the user's templated kernels.
// ----------------------------------------------------------------------------
using RegisterFn = void (*)(const char* id, const TgmrfSpec* spec);

} // namespace tgmrf_backend
} // namespace tulpa

// ----------------------------------------------------------------------------
// TULPA_REGISTER_TGMRF(ID, Q_FN, MU_FN, LOG_PRIOR_FN)
//
// One-call registration boilerplate for user .cpp files. See the file
// header for usage.
//
// Expansion produces (inside an anonymous namespace, so the macro is safe
// to use once per translation unit):
//   * Explicit instantiations of Q_FN<double>, MU_FN<double>,
//     LOG_PRIOR_FN<double>.
//   * A `TgmrfSpec` populated with those instantiations.
//   * A static initializer that resolves
//     `R_GetCCallable("tulpa", "tulpa_register_tgmrf")` and forwards the
//     spec under `ID`.
// ----------------------------------------------------------------------------
#define TULPA_REGISTER_TGMRF(ID, Q_FN, MU_FN, LOG_PRIOR_FN)                    \
/* Explicit instantiations must live at namespace scope of the */              \
/* templates' enclosing namespace (here :: -- the user's functions */          \
/* live at file scope). */                                                     \
template Eigen::SparseMatrix<double> Q_FN<double>(                             \
    const Eigen::Matrix<double, Eigen::Dynamic, 1>&);                          \
template Eigen::Matrix<double, Eigen::Dynamic, 1> MU_FN<double>(               \
    const Eigen::Matrix<double, Eigen::Dynamic, 1>&);                          \
template double LOG_PRIOR_FN<double>(                                          \
    const Eigen::Matrix<double, Eigen::Dynamic, 1>&);                          \
                                                                               \
namespace {                                                                    \
    inline tulpa::tgmrf_backend::TgmrfSpec tulpa_tgmrf_build_spec() {          \
        tulpa::tgmrf_backend::TgmrfSpec s;                                     \
        s.Q_double         = &Q_FN<double>;                                    \
        s.mu_double        = &MU_FN<double>;                                   \
        s.log_prior_double = &LOG_PRIOR_FN<double>;                            \
        s.Q_arena          = nullptr;                                          \
        s.mu_arena         = nullptr;                                          \
        s.log_prior_arena  = nullptr;                                          \
        s.Q_fwd            = nullptr;                                          \
        s.mu_fwd           = nullptr;                                          \
        s.log_prior_fwd    = nullptr;                                          \
        return s;                                                              \
    }                                                                          \
                                                                               \
    inline int tulpa_tgmrf_register_at_load() {                                \
        static tulpa::tgmrf_backend::TgmrfSpec s = tulpa_tgmrf_build_spec();   \
        auto fp = (tulpa::tgmrf_backend::RegisterFn) R_GetCCallable(           \
            "tulpa", "tulpa_register_tgmrf");                                  \
        if (fp != nullptr) fp(ID, &s);                                         \
        return 1;                                                              \
    }                                                                          \
                                                                               \
    static int tulpa_tgmrf_registration_dummy =                                \
        tulpa_tgmrf_register_at_load();                                        \
}                                                                              \
                                                                               \
/* Rcpp::sourceCpp requires at least one [[Rcpp::export]] symbol in the */     \
/* compilation unit before it will dyn.load the resulting DLL. Without */      \
/* the load step, our static initialiser never fires and the spec never */     \
/* lands in the registry. We expose a trivial helper that the R-side */        \
/* constructor calls back to confirm the load fired and the id matches. */     \
/* [[Rcpp::export]] */                                                         \
inline std::string tulpa_tgmrf_cpp_id() { return std::string(ID); }

#endif // TULPA_TGMRF_H
