# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_flatten_3d_rowmajor <- function(arr, d1, d2, d3) {
    .Call(`_tulpa_cpp_flatten_3d_rowmajor`, arr, d1, d2, d3)
}

cpp_sample_crt <- function(y, r) {
    .Call(`_tulpa_cpp_sample_crt`, y, r)
}

cpp_sample_crt_sum <- function(y, r) {
    .Call(`_tulpa_cpp_sample_crt_sum`, y, r)
}

cpp_crt_mean <- function(y, r) {
    .Call(`_tulpa_cpp_crt_mean`, y, r)
}

cpp_ess_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, seed, verbose) {
    .Call(`_tulpa_cpp_ess_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, seed, verbose)
}

cpp_ess_get_n_params <- function(X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params) {
    .Call(`_tulpa_cpp_ess_get_n_params`, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params)
}

cpp_gibbs_spatial <- function(data_list) {
    .Call(`_tulpa_cpp_gibbs_spatial`, data_list)
}

cpp_gpu_available <- function() {
    .Call(`_tulpa_cpp_gpu_available`)
}

cpp_gpu_info <- function() {
    .Call(`_tulpa_cpp_gpu_info`)
}

cpp_hmc_fit <- function(q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, tvc_params, svc_params, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, gradient_mode_str = "auto", max_treedepth = 10L, metric_str = "auto", adapt_delta = -1.0, riemannian = -1L, gradient_check_only = FALSE) {
    .Call(`_tulpa_cpp_hmc_fit`, q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, tvc_params, svc_params, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, gradient_mode_str, max_treedepth, metric_str, adapt_delta, riemannian, gradient_check_only)
}

cpp_hmc_fit_gp <- function(q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, gp_params, ms_gp_params, ms_temporal_params, rsr_params, temporal_params, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, max_treedepth = 10L, adapt_delta = -1.0, metric_str = "auto", gradient_mode_str = "auto", tvc_params = NULL, gradient_check_only = FALSE) {
    .Call(`_tulpa_cpp_hmc_fit_gp`, q_init, y_num, y_denom, y_num_cont, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, gp_params, ms_gp_params, ms_temporal_params, rsr_params, temporal_params, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose, max_treedepth, adapt_delta, metric_str, gradient_mode_str, tvc_params, gradient_check_only)
}

cpp_hmc_fit_gp_v2 <- function(args) {
    .Call(`_tulpa_cpp_hmc_fit_gp_v2`, args)
}

cpp_get_max_threads <- function() {
    .Call(`_tulpa_cpp_get_max_threads`)
}

cpp_spde_laplace_gradient <- function(y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, log_range, log_sigma, nu = 1.0, family = "binomial", phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_spde_laplace_gradient`, y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, log_range, log_sigma, nu, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_laplace_fit <- function(y, n, X, re_idx, n_re_groups, sigma_re, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit`, y, n, X, re_idx, n_re_groups, sigma_re, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_fit_multi_re <- function(y, n, X, re_idx_list, re_ngroups, re_sigma_list, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L, re_Z_list = NULL, re_ncoefs = NULL, weights = NULL, offset = NULL, x_init = NULL) {
    .Call(`_tulpa_cpp_laplace_fit_multi_re`, y, n, X, re_idx_list, re_ngroups, re_sigma_list, family, phi, max_iter, tol, n_threads, re_Z_list, re_ncoefs, weights, offset, x_init)
}

cpp_laplace_sample <- function(mode, H, n_samples) {
    .Call(`_tulpa_cpp_laplace_sample`, mode, H, n_samples)
}

cpp_laplace_fit_gp <- function(y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_gp, phi_gp, cov_type, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit_gp`, y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_gp, phi_gp, cov_type, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_fit_multiscale_gp <- function(y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, n_spatial, sigma2_local, phi_local, sigma2_regional, phi_regional, cov_type, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit_multiscale_gp`, y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, n_spatial, sigma2_local, phi_local, sigma2_regional, phi_regional, cov_type, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_fit_multiscale_temporal <- function(y, n, X, re_idx, n_re_groups, sigma_re, time_idx, n_times, seasonal_period, trend_type, short_type, sigma2_trend, sigma2_seasonal, sigma2_short, rho_short, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit_multiscale_temporal`, y, n, X, re_idx, n_re_groups, sigma_re, time_idx, n_times, seasonal_period, trend_type, short_type, sigma2_trend, sigma2_seasonal, sigma2_short, rho_short, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_fit_spatial <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_laplace_fit_spatial`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_laplace_fit_bym2 <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, sigma_spatial, rho, scale_factor, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit_bym2`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, sigma_spatial, rho, scale_factor, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_fit_rsr <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, rsr_projection, rsr_n, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_fit_rsr`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, rsr_projection, rsr_n, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_spec_test_gaussian <- function(y, X, re_idx, n_re_groups, sigma_re, sigma_beta, phi, max_iter = 100L, tol = 1e-8, n_threads = 1L) {
    .Call(`_tulpa_cpp_laplace_spec_test_gaussian`, y, X, re_idx, n_re_groups, sigma_re, sigma_beta, phi, max_iter, tol, n_threads)
}

cpp_mclmc_test <- function(mu_target, sigma_target, init, n_iter = 2000L, n_warmup = 1000L, seed = 42L, adjusted = FALSE) {
    .Call(`_tulpa_cpp_mclmc_test`, mu_target, sigma_target, init, n_iter, n_warmup, seed, adjusted)
}

cpp_nested_laplace_icar <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_icar`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_bym2 <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, scale_factor, sigma_spatial_grid, rho_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_bym2`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, scale_factor, sigma_spatial_grid, rho_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_car_proper <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, rho_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_car_proper`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_grid, rho_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_rw1 <- function(y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, cyclic, tau_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_rw1`, y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, cyclic, tau_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_rw2 <- function(y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, tau_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_rw2`, y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, tau_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_ar1 <- function(y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, tau_grid, rho_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_ar1`, y, n, X, re_idx, n_re_groups, sigma_re, temporal_idx, n_times, tau_grid, rho_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_nngp <- function(y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_grid, phi_gp_grid, cov_type, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_nngp`, y, n, X, re_idx, n_re_groups, sigma_re, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_grid, phi_gp_grid, cov_type, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_nested_laplace_hsgp <- function(y, n, X, re_idx, n_re_groups, sigma_re, phi_basis, lambda_eig, sigma2_grid, lengthscale_grid, family, phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_hsgp`, y, n, X, re_idx, n_re_groups, sigma_re, phi_basis, lambda_eig, sigma2_grid, lengthscale_grid, family, phi, max_iter, tol, n_threads, x_init_nullable)
}

cpp_pg_binomial_gibbs <- function(y, n, X, group, n_groups, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_scale = 2.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs`, y, n, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_spatial <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_tau_shape = 1.0, prior_tau_rate = 0.01, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_spatial`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_bym2 <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_spatial_scale = 2.5, prior_rho_alpha = 0.5, prior_rho_beta = 0.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_bym2`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_spatial_scale, prior_rho_alpha, prior_rho_beta, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_gp <- function(y, n, X, re_group, n_re_groups, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_gp_init, phi_gp_init, cov_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_gp_U = 1.0, prior_sigma_gp_alpha = 0.01, prior_phi_lower = 0.01, prior_phi_upper = 10.0, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_gp`, y, n, X, re_group, n_re_groups, coords, nn_idx, nn_dist, nn_order, n_spatial, nn, sigma2_gp_init, phi_gp_init, cov_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_gp_U, prior_sigma_gp_alpha, prior_phi_lower, prior_phi_upper, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_multiscale_gp <- function(y, n, X, re_group, n_re_groups, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, n_spatial, sigma2_local_init, phi_local_init, sigma2_regional_init, phi_regional_init, cov_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_local_U = 1.0, prior_sigma_local_alpha = 0.01, prior_phi_local_lower = 0.01, prior_phi_local_upper = 5.0, prior_sigma_regional_U = 1.0, prior_sigma_regional_alpha = 0.01, prior_phi_regional_lower = 0.1, prior_phi_regional_upper = 20.0, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_multiscale_gp`, y, n, X, re_group, n_re_groups, coords, nn_idx_local, nn_dist_local, nn_order_local, nn_local, nn_idx_regional, nn_dist_regional, nn_order_regional, nn_regional, n_spatial, sigma2_local_init, phi_local_init, sigma2_regional_init, phi_regional_init, cov_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_local_U, prior_sigma_local_alpha, prior_phi_local_lower, prior_phi_local_upper, prior_sigma_regional_U, prior_sigma_regional_alpha, prior_phi_regional_lower, prior_phi_regional_upper, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_rsr <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, rsr_projection, rsr_n, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_tau_shape = 1.0, prior_tau_rate = 0.01, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_rsr`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, rsr_projection, rsr_n, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_temporal <- function(y, n, X, re_group, n_re_groups, time_idx, n_times, seasonal_period, trend_type, short_type, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_trend_scale = 1.0, prior_sigma_seasonal_scale = 1.0, prior_sigma_short_scale = 1.0, rho_short_init = 0.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_tulpa_cpp_pg_binomial_gibbs_temporal`, y, n, X, re_group, n_re_groups, time_idx, n_times, seasonal_period, trend_type, short_type, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_trend_scale, prior_sigma_seasonal_scale, prior_sigma_short_scale, rho_short_init, store_eta, verbose, n_threads)
}

cpp_pg_negbin_gibbs <- function(y, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads) {
    .Call(`_tulpa_cpp_pg_negbin_gibbs`, y, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads)
}

cpp_pg_negbin_negbin_gibbs <- function(y_num, y_denom, X_num, X_denom, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_num_init, r_denom_init, shared, store_eta, verbose, n_threads) {
    .Call(`_tulpa_cpp_pg_negbin_negbin_gibbs`, y_num, y_denom, X_num, X_denom, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, prior_r_shape, prior_r_rate, r_num_init, r_denom_init, shared, store_eta, verbose, n_threads)
}

cpp_pg_negbin_gibbs_spatial <- function(y, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads) {
    .Call(`_tulpa_cpp_pg_negbin_gibbs_spatial`, y, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, prior_r_shape, prior_r_rate, r_init, store_eta, verbose, n_threads)
}

cpp_rpg1 <- function(z) {
    .Call(`_tulpa_cpp_rpg1`, z)
}

cpp_rpg <- function(b, z) {
    .Call(`_tulpa_cpp_rpg`, b, z)
}

cpp_sghmc_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, alpha, L, seed, verbose) {
    .Call(`_tulpa_cpp_sghmc_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, alpha, L, seed, verbose)
}

cpp_sgld_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, schedule_a, schedule_b, schedule_gamma, use_schedule, seed, verbose) {
    .Call(`_tulpa_cpp_sgld_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, n_iter, n_warmup, batch_size, epsilon, schedule_a, schedule_b, schedule_gamma, use_schedule, seed, verbose)
}

cpp_smc_test <- function(mu_target, sigma_target, n_particles = 500L, n_mcmc_steps = 5L, seed = 42L) {
    .Call(`_tulpa_cpp_smc_test`, mu_target, sigma_target, n_particles, n_mcmc_steps, seed)
}

cpp_selected_inversion_diagonal <- function(Q_x, Q_i, Q_p, n) {
    .Call(`_tulpa_cpp_selected_inversion_diagonal`, Q_x, Q_i, Q_p, n)
}

cpp_laplace_fit_spde <- function(y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, kappa, tau_spde, family, phi = 1.0, alpha = 2L, max_iter = 100L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL, rational_poles_nullable = NULL, rational_weights_nullable = NULL) {
    .Call(`_tulpa_cpp_laplace_fit_spde`, y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, kappa, tau_spde, family, phi, alpha, max_iter, tol, n_threads, x_init_nullable, rational_poles_nullable, rational_weights_nullable)
}

cpp_nested_laplace_spde <- function(y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, range_grid, sigma_grid, nu = 1.0, family = "binomial", phi = 1.0, max_iter = 50L, tol = 1e-6, n_threads = 1L, x_init_nullable = NULL, rational_poles_nullable = NULL, rational_weights_nullable = NULL) {
    .Call(`_tulpa_cpp_nested_laplace_spde`, y, n_trials, X, A_x, A_i, A_p, n_obs, n_mesh, C0_diag, G1_x, G1_i, G1_p, range_grid, sigma_grid, nu, family, phi, max_iter, tol, n_threads, x_init_nullable, rational_poles_nullable, rational_weights_nullable)
}

cpp_stochastic_log_determinant <- function(Q_x, Q_i, Q_p, n, n_probes = 30L, n_lanczos = 50L, seed = 42L) {
    .Call(`_tulpa_cpp_stochastic_log_determinant`, Q_x, Q_i, Q_p, n, n_probes, n_lanczos, seed)
}

cpp_test_leapfrog <- function(q_init, p_init, epsilon, L) {
    .Call(`_tulpa_cpp_test_leapfrog`, q_init, p_init, epsilon, L)
}

cpp_test_hamiltonian <- function(q, p) {
    .Call(`_tulpa_cpp_test_hamiltonian`, q, p)
}

cpp_test_log_sum_exp <- function(log_vals) {
    .Call(`_tulpa_cpp_test_log_sum_exp`, log_vals)
}

cpp_test_softmax <- function(x) {
    .Call(`_tulpa_cpp_test_softmax`, x)
}

cpp_test_inv_logit <- function(x) {
    .Call(`_tulpa_cpp_test_inv_logit`, x)
}

cpp_test_lgamma <- function(x) {
    .Call(`_tulpa_cpp_test_lgamma`, x)
}

cpp_test_poisson_loglik <- function(y, lambda) {
    .Call(`_tulpa_cpp_test_poisson_loglik`, y, lambda)
}

cpp_test_binomial_loglik <- function(y, n, p) {
    .Call(`_tulpa_cpp_test_binomial_loglik`, y, n, p)
}

cpp_test_negbin_loglik <- function(y, mu, phi) {
    .Call(`_tulpa_cpp_test_negbin_loglik`, y, mu, phi)
}

cpp_test_normal_loglik <- function(y, mu, sigma) {
    .Call(`_tulpa_cpp_test_normal_loglik`, y, mu, sigma)
}

cpp_test_cholesky <- function(A) {
    .Call(`_tulpa_cpp_test_cholesky`, A)
}

cpp_test_matvec <- function(A, x) {
    .Call(`_tulpa_cpp_test_matvec`, A, x)
}

cpp_test_autodiff_gradient <- function(x_vals) {
    .Call(`_tulpa_cpp_test_autodiff_gradient`, x_vals)
}

cpp_test_autodiff_exp_chain <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_exp_chain`, x_val)
}

cpp_test_autodiff_log_likelihood <- function(y, eta) {
    .Call(`_tulpa_cpp_test_autodiff_log_likelihood`, y, eta)
}

cpp_test_autodiff_division <- function(a_val, b_val) {
    .Call(`_tulpa_cpp_test_autodiff_division`, a_val, b_val)
}

cpp_test_autodiff_lgamma <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_lgamma`, x_val)
}

cpp_test_autodiff_softplus <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_softplus`, x_val)
}

cpp_test_autodiff_inv_logit <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_inv_logit`, x_val)
}

cpp_test_autodiff_log <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_log`, x_val)
}

cpp_test_autodiff_sqrt <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_sqrt`, x_val)
}

cpp_test_autodiff_pow <- function(x_val, p) {
    .Call(`_tulpa_cpp_test_autodiff_pow`, x_val, p)
}

cpp_test_autodiff_log1p <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_log1p`, x_val)
}

cpp_test_autodiff_log_sum_exp <- function(a_val, b_val) {
    .Call(`_tulpa_cpp_test_autodiff_log_sum_exp`, a_val, b_val)
}

cpp_test_autodiff_logit <- function(x_val) {
    .Call(`_tulpa_cpp_test_autodiff_logit`, x_val)
}

cpp_test_autodiff_negbin_loglik <- function(y, mu, phi) {
    .Call(`_tulpa_cpp_test_autodiff_negbin_loglik`, y, mu, phi)
}

cpp_test_laplace_binomial <- function(y, n, eta) {
    .Call(`_tulpa_cpp_test_laplace_binomial`, y, n, eta)
}

cpp_test_laplace_negbin <- function(y, eta, phi) {
    .Call(`_tulpa_cpp_test_laplace_negbin`, y, eta, phi)
}

cpp_test_laplace_poisson <- function(y, eta) {
    .Call(`_tulpa_cpp_test_laplace_poisson`, y, eta)
}

cpp_test_pg_update_beta <- function(kappa, omega, X, re_contrib, prior_sd) {
    .Call(`_tulpa_cpp_test_pg_update_beta`, kappa, omega, X, re_contrib, prior_sd)
}

cpp_test_pg_update_re <- function(kappa, omega, X_beta, group, n_groups, sigma_re) {
    .Call(`_tulpa_cpp_test_pg_update_re`, kappa, omega, X_beta, group, n_groups, sigma_re)
}

cpp_test_pg_update_sigma_re <- function(re, scale) {
    .Call(`_tulpa_cpp_test_pg_update_sigma_re`, re, scale)
}

cpp_test_dot_product <- function(x, y) {
    .Call(`_tulpa_cpp_test_dot_product`, x, y)
}

cpp_test_norm_squared <- function(x) {
    .Call(`_tulpa_cpp_test_norm_squared`, x)
}

cpp_test_vector_sum <- function(x) {
    .Call(`_tulpa_cpp_test_vector_sum`, x)
}

cpp_test_axpy <- function(a, x, y) {
    .Call(`_tulpa_cpp_test_axpy`, a, x, y)
}

cpp_test_scale <- function(a, x) {
    .Call(`_tulpa_cpp_test_scale`, a, x)
}

cpp_test_linalg_matvec <- function(X, beta) {
    .Call(`_tulpa_cpp_test_linalg_matvec`, X, beta)
}

cpp_test_linalg_matvec_add <- function(X, beta, y_init) {
    .Call(`_tulpa_cpp_test_linalg_matvec_add`, X, beta, y_init)
}

cpp_test_linalg_matvec_transpose <- function(X, x) {
    .Call(`_tulpa_cpp_test_linalg_matvec_transpose`, X, x)
}

cpp_test_sparse_laplacian_quadform <- function(row_ptr, col_idx, x) {
    .Call(`_tulpa_cpp_test_sparse_laplacian_quadform`, row_ptr, col_idx, x)
}

cpp_test_linalg_log_sum_exp <- function(a, b) {
    .Call(`_tulpa_cpp_test_linalg_log_sum_exp`, a, b)
}

cpp_test_linalg_log_sum_exp_vec <- function(x) {
    .Call(`_tulpa_cpp_test_linalg_log_sum_exp_vec`, x)
}

cpp_test_softmax_inplace <- function(x) {
    .Call(`_tulpa_cpp_test_softmax_inplace`, x)
}

cpp_test_compute_linear_predictors <- function(X_num, beta_num, X_denom, beta_denom, n_threads) {
    .Call(`_tulpa_cpp_test_compute_linear_predictors`, X_num, beta_num, X_denom, beta_denom, n_threads)
}

cpp_test_rw1_quadratic_form <- function(phi, cyclic) {
    .Call(`_tulpa_cpp_test_rw1_quadratic_form`, phi, cyclic)
}

cpp_test_rw2_quadratic_form <- function(phi, cyclic) {
    .Call(`_tulpa_cpp_test_rw2_quadratic_form`, phi, cyclic)
}

cpp_test_ar1_log_density <- function(phi, rho, tau) {
    .Call(`_tulpa_cpp_test_ar1_log_density`, phi, rho, tau)
}

cpp_test_temporal_log_prior <- function(phi, type_str, tau, rho, cyclic) {
    .Call(`_tulpa_cpp_test_temporal_log_prior`, phi, type_str, tau, rho, cyclic)
}

cpp_test_sum_to_zero_penalty <- function(phi, lambda) {
    .Call(`_tulpa_cpp_test_sum_to_zero_penalty`, phi, lambda)
}

cpp_test_log1pexp <- function(x) {
    .Call(`_tulpa_cpp_test_log1pexp`, x)
}

cpp_test_zi_logistic <- function(x) {
    .Call(`_tulpa_cpp_test_zi_logistic`, x)
}

cpp_test_log_logistic <- function(x) {
    .Call(`_tulpa_cpp_test_log_logistic`, x)
}

cpp_test_log1m_logistic <- function(x) {
    .Call(`_tulpa_cpp_test_log1m_logistic`, x)
}

cpp_test_zi_poisson_lpmf <- function(y, mu) {
    .Call(`_tulpa_cpp_test_zi_poisson_lpmf`, y, mu)
}

cpp_test_zi_negbin_lpmf <- function(y, mu, phi) {
    .Call(`_tulpa_cpp_test_zi_negbin_lpmf`, y, mu, phi)
}

cpp_test_zi_poisson_lpmf_logit <- function(y, mu, logit_zi) {
    .Call(`_tulpa_cpp_test_zi_poisson_lpmf_logit`, y, mu, logit_zi)
}

cpp_test_zi_negbin_lpmf_logit <- function(y, mu, phi, logit_zi) {
    .Call(`_tulpa_cpp_test_zi_negbin_lpmf_logit`, y, mu, phi, logit_zi)
}

cpp_test_truncated_poisson_lpmf <- function(y, mu) {
    .Call(`_tulpa_cpp_test_truncated_poisson_lpmf`, y, mu)
}

cpp_test_truncated_negbin_lpmf <- function(y, mu, phi) {
    .Call(`_tulpa_cpp_test_truncated_negbin_lpmf`, y, mu, phi)
}

cpp_test_hurdle_poisson_lpmf_logit <- function(y, mu, logit_theta) {
    .Call(`_tulpa_cpp_test_hurdle_poisson_lpmf_logit`, y, mu, logit_theta)
}

cpp_test_hurdle_negbin_lpmf_logit <- function(y, mu, phi, logit_theta) {
    .Call(`_tulpa_cpp_test_hurdle_negbin_lpmf_logit`, y, mu, phi, logit_theta)
}

cpp_test_zi_log_likelihood <- function(y, mu, phi, logit_zi, zi_type_str) {
    .Call(`_tulpa_cpp_test_zi_log_likelihood`, y, mu, phi, logit_zi, zi_type_str)
}

cpp_test_zi_poisson_grad_logit_zi <- function(y, mu, logit_zi) {
    .Call(`_tulpa_cpp_test_zi_poisson_grad_logit_zi`, y, mu, logit_zi)
}

cpp_test_zi_negbin_grad_logit_zi <- function(y, mu, phi, logit_zi) {
    .Call(`_tulpa_cpp_test_zi_negbin_grad_logit_zi`, y, mu, phi, logit_zi)
}

cpp_test_hurdle_grad_logit_theta <- function(y, logit_theta) {
    .Call(`_tulpa_cpp_test_hurdle_grad_logit_theta`, y, logit_theta)
}

cpp_test_parallel_dot_products <- function(X, y, n_threads) {
    .Call(`_tulpa_cpp_test_parallel_dot_products`, X, y, n_threads)
}

cpp_test_parallel_likelihood <- function(y, mu, n_threads) {
    .Call(`_tulpa_cpp_test_parallel_likelihood`, y, mu, n_threads)
}

cpp_test_parallel_independent <- function(n, n_threads) {
    .Call(`_tulpa_cpp_test_parallel_independent`, n, n_threads)
}

cpp_test_gp_solver_dispatch <- function(w, sigma2, phi, coords, nn_idx, nn_dist, nn_neighbor_dist, nn_order, nn_order_inv, cov_type, solver, cg_tol, cg_maxiter) {
    .Call(`_tulpa_cpp_test_gp_solver_dispatch`, w, sigma2, phi, coords, nn_idx, nn_dist, nn_neighbor_dist, nn_order, nn_order_inv, cov_type, solver, cg_tol, cg_maxiter)
}

cpp_test_lkj_build_L <- function(raw, n) {
    .Call(`_tulpa_cpp_test_lkj_build_L`, raw, n)
}

cpp_test_lkj_density <- function(L, eta) {
    .Call(`_tulpa_cpp_test_lkj_density`, L, eta)
}

cpp_test_lkj_grad <- function(raw, n, eta) {
    .Call(`_tulpa_cpp_test_lkj_grad`, raw, n, eta)
}

cpp_test_compute_u_eff <- function(L, sigma, z) {
    .Call(`_tulpa_cpp_test_compute_u_eff`, L, sigma, z)
}

cpp_test_chol_nc_chain_rule <- function(L, sigma, z, raw, u_eff, glik) {
    .Call(`_tulpa_cpp_test_chol_nc_chain_rule`, L, sigma, z, raw, u_eff, glik)
}

cpp_test_correlation_from_L <- function(L) {
    .Call(`_tulpa_cpp_test_correlation_from_L`, L)
}

cpp_compute_log_post_test <- function(params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params) {
    .Call(`_tulpa_cpp_compute_log_post_test`, params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params)
}

cpp_compute_log_prior_test <- function(params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params) {
    .Call(`_tulpa_cpp_compute_log_prior_test`, params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params)
}

cpp_compute_log_lik_only_test <- function(params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params) {
    .Call(`_tulpa_cpp_compute_log_lik_only_test`, params, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params)
}

cpp_log_post_split_n_params <- function(y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params) {
    .Call(`_tulpa_cpp_log_post_split_n_params`, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params)
}

cpp_tulpa_fit_gaussian <- function(y_r, X_r, sigma_beta = 10.0, n_iter = 2000L, n_warmup = 1000L, step_size = 0.05, n_leapfrog = 10L, seed = 42L) {
    .Call(`_tulpa_cpp_tulpa_fit_gaussian`, y_r, X_r, sigma_beta, n_iter, n_warmup, step_size, n_leapfrog, seed)
}

cpp_tulpa_fit_generic <- function(y_r, X_r, sigma_beta = 10.0, n_iter = 2000L, n_warmup = 1000L, max_treedepth = 10L, adapt_delta = 0.8, seed = 42L, verbose = TRUE) {
    .Call(`_tulpa_cpp_tulpa_fit_generic`, y_r, X_r, sigma_beta, n_iter, n_warmup, max_treedepth, adapt_delta, seed, verbose)
}

tulpa_version <- function() {
    .Call(`_tulpa_tulpa_version`)
}

cpp_vi_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, vi_options, verbose = TRUE) {
    .Call(`_tulpa_cpp_vi_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, prior_params, zi_params, latent_params, st_params, vi_options, verbose)
}

cpp_vi_get_n_params <- function(X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params, latent_params) {
    .Call(`_tulpa_cpp_vi_get_n_params`, X_num, X_denom, model_type_str, re_params, spatial_params, temporal_params, zi_params, latent_params)
}

